# Generated by Django 6.0.2 on 2026-02-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
